mySelfApp/urls.py
from django.urls import path
from . import views

app_name = 'myself'

urlpatterns = [
    path('', views.main_view, name='main_view'),
    path('observation/', views.observation_view, name='observation_view'),
    path('situation/', views.situation_view, name='situation_view'),
    path('add_observation/', views.add_observation, name='add_observation'),
    path('get_observation/', views.get_observation, name='get_observation'),
    path('get_choice/', views.get_choice, name='get_choice'),
    path('stats_Activities/', views.stats_view_activities, name='stats_view_activities'),
    path('stats_Objects/', views.stats_view_objects, name='stats_view_objects'),
    path('stats_Contexts/', views.stats_view_contexts, name='stats_view_contexts'),
    path('stats_Bridges/', views.stats_view_emotional_bridge, name='stats_view_emotional_bridge'),
    path('remove_log/<int:log_id>/<str:target>/', views.remove_log, name='stats_view_emotional_bridge'),

]

myself/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mySelfApp.urls'))
]

mySelfApp/models.py
from django.db import models
import json
import sys
import csv
import pandas as pd
import numpy as np

#adding the directory where I have the words for the main model.
sys.path.append('/home/gilberto/workspace/projectos/myself/mySelfApp/words/')

class counter(models.Model):
    name = models.CharField(max_length=100)
    count = models.IntegerField(default=0)

#Classes
class Sentence(models.Model):
    text = models.CharField(max_length=200)
    target = models.CharField(max_length=100, default='')
    verbs = models.CharField(max_length=150, default='')
    booleans = models.CharField(max_length=100, default='') #1: positive, 2:negative, 0:none
    emotions = models.CharField(max_length=150, default='')
    sign = models.CharField(max_length=10, default='') #true, false
    action = models.IntegerField(default=0)
    unaction = models.IntegerField(default=0)
    text = text

    def __str__(self):
        return '\ntext: {}\ndb: {}\nverbs: {},\nemotions: {}\nsign: {}, booleans: {}\n'.format(self.text, self.target, self.verbs, self.emotions, self.sign, self.booleans)

    #STATS 
    def get_stats_data(self):
        data:dict = {
            'Activities': Sentence.objects.filter(target='user_emotion_actions'),
            'Objects': Sentence.objects.filter(target='user_emotion_objects'),
            'Contexts': Sentence.objects.filter(target='user_emotion_context'),
            'Bridges': Sentence.objects.filter(target='user_emotion_bridge'),
        }
        return data 

    #INSERT SITUATION
    def user_response(self, text:str):
        isList = True
        ans = ''
        #getting list word
        if 'list' not in text:
            isList = False
        #getting emotions

        if isList:
            response, message = self.list_response(text)
        #Emotion bridge answer
        else:
            response, message = self.emotional_bridge_response(text)
        return response, message

    def emotional_bridge_response(self, text:str):
        message = 'This is a memory of how you faced a similar situation: '
        emotions = self.get_words_from_category(self.remove_signs(text), 'emotions')
        db_sentences = Sentence.objects.filter(target="user_emotion_bridge")
        sentences = {}

        #filter all the sentences that includes the ones that has the emotion that I mentioned
        for emotion in emotions:
            sentences[emotion] = []
            for sentence in db_sentences:
                s_emotions = json.loads(sentence.emotions)
                if emotion in s_emotions[0]:
                    sentences[emotion].append(sentence)

        #get the best result from all
        response = {'text': '', 'repeated_words': 0, 'id': None}
        for key, value in sentences.items():
            for el in value:
                counter = self.count_repeated_words(el.text, text)
                if(counter > response['repeated_words']):
                    response = {'text': el.text, 'repeated_words': counter, 'id': el.id}

        #restruct the response
        print(response)
        return  response, message

    def get_movement_percentage(self):
        positive, negative = self.get_total_movements()
        total = positive + negative
        if(total == 0): return 0
        percentage = (positive * 100) / total
        return percentage
    
    def list_response(self, text:str):
        print('GetAnswerQuerty()')
        text =  " ".join(" ".join(text.split('.')).split(','))
        sentences = []
        selected_sentence = {'text': '', 'words': 0}
        verbs = self.get_words_from_category(sentence=text, category='verbs')
        message = 'This is a list of things you like to {}'.format(", ".join(verbs))
        print(text)
        if len(verbs) > 0:
            for i in range(len(verbs)):
                if 'things' in text and verbs[i] in text:
                    print('#actions section#')
                    db_sentences = Sentence.objects.filter(target='user_emotion_actions')
                    print(db_sentences)
                    boolean = self.get_words_from_category(text, 'negative_booleans') or True
                    emotions = self.get_words_from_category(text, 'emotions') 
                    print(boolean)
                    print(emotions)
                    print(verbs[i])
                    #filter by booleans and emotions
                    for s in db_sentences:
                        for j in range(len(emotions)):
                            print(j)
                            print(json.loads(s.booleans))
                            print(json.loads(s.emotions)[0][0])
                            print(json.loads(s.verbs)[0][0])
                            if json.loads(s.booleans)[0] == boolean and json.loads(s.emotions)[0][0] == emotions[j] and json.loads(s.verbs)[i][0] == verbs[i]:
                                sentences.append(s)
                    return sentences, message

        if 'things' in text:
            #e.x.sentence: list of things I like
            print('#things section#')
            db_sentences = Sentence.objects.filter(target='user_emotion_object')
            boolean = self.get_words_from_category(text, 'negative_booleans') or True
            emotions = self.get_words_from_category(text, 'emotions') 
            sentences = []

            for s in db_sentences:
                for j in range(len(emotions)):
                    print(j)
                    print(json.loads(s.booleans))
                    print(json.loads(s.emotions)[0][0])
                    if json.loads(s.booleans)[0] == boolean and json.loads(s.emotions)[0][0] == emotions[j]:
                        sentences.append(s)
            return sentences, message

        else:
            print('#context section#')
            db_sentences = Sentence.objects.filter(target='user_emotion_context')
            boolean = self.get_words_from_category(text, 'negative_booleans') or True
            emotions = self.get_words_from_category(text, 'emotions') 
            sentences = []

            for s in db_sentences:
                for j in range(len(emotions)):
                    print(j)
                    print(json.loads(s.booleans))
                    print(json.loads(s.emotions))
                    print(json.loads(s.emotions)[0][0])
                    if json.loads(s.booleans)[0] == boolean and json.loads(s.emotions)[0][0] == emotions[j]:
                        sentences.append(s)
            return sentences, message




    #INSERT OBSERVATION (DONE)
    def analyzeSentence(self):
        # print('\nanalyseSentence():')
        sentences_data:dict = self.get_sentences_data()
        #do nothing if there is no sentences
        if(sentences_data == {}): return True
        #TODO: Insertar el apartado "insertSentenceToDB()" 
        self.insertSentenceToDB(sentences_data)

    @classmethod
    def insertSentenceToDB(cls, sentences_data:dict):
        for i in range(len(sentences_data['sentences'])):
            s = cls(text=sentences_data['sentences'][i],
                    emotions=json.dumps(sentences_data['emotions'][i]),
                    verbs=json.dumps(sentences_data['verbs'][i]),
                    booleans=json.dumps(sentences_data['booleans'][i]),
                    sign=json.dumps(sentences_data['signs'][i]),
                    target=sentences_data['target'][i],
                    )
            s.save()

    def get_sentences_data(self):
        sentences = self.select_emotional_sentences()
        #do nothing if there is no sentences
        if(len(sentences) < 1): return dict({})
        sentences_data = {
            'sentences': sentences,
            'emotions': [],
            'signs': [],
            'booleans': [],
            'target': [],
            'verbs': [],
        }
        i = 0
        while i < len(sentences):
            sub_sentences = sentences[i].split(',') 
            #filling some extra information
            sentences_data['emotions'].append(self.get_divided_words_from_categories(sentences[i], 'emotions')) #TODO: Hacer una funcion similar a get_booleans() para las emociones y los verbos (done!)
            sentences_data['booleans'].append(self.get_booleans(sentences[i]))
            sentences_data['verbs'].append(self.get_divided_words_from_categories(sentences[i], 'verbs'))

            #potencialy compund sentences
            if len(sub_sentences) > 1:
                sub_sentence_categories = self.get_words_categories(sub_sentences[0])
                next_sub_sentence_categories = self.get_words_categories(sub_sentences[1])
                #case 1: emotional bridge
                if 'emotions' in sub_sentence_categories and 'emotions' in next_sub_sentence_categories:
                    if self.is_positive(self.get_words_from_category(sub_sentences[i], 'emotions')) == False and self.is_positive(self.get_words_from_category(sub_sentences[i+1], 'emotions')):
                        sentences_data['target'].append('user_emotion_bridge')
                        sentences_data['signs'].append([False, True])
                        i += 1
                        continue
            #case 2: emotional with action sentence
            sub_sentence_categories = self.get_words_categories(sub_sentences[0])
            if 'verbs' in sub_sentence_categories:
                sentences_data['target'].append('user_emotion_actions')
                sub_sentence = " ".join(" ".join(sub_sentences).split(',')) #get an string without . and , 
                sentences_data['signs'].append(self.is_positive(sub_sentence))
                i += 1
                continue
            #case 3: emotional with objects
            elif 'object' in sub_sentence_categories and 'verbs' not in sub_sentence_categories:
                sentences_data['target'].append('user_emotion_object')
                sub_sentence = " ".join(" ".join(sub_sentences).split(',')) #get an string without . and , 

mySelfApp/views.py
from django.shortcuts import render
from django.db.models import F
from .models import Sentence

# Create your views here.

def main_view(request):
    s = Sentence.objects.all()[0]
    percentage = s.get_movement_percentage()
    return render(request,'main_view.html',{'percentage': percentage})

def observation_view(request):
    return render(request,'chat_view.html',{'title': 'observation', 'form_path': '/add_observation/', 'message': 'Please insert a new observation'})

def situation_view(request):
    return render(request,'chat_view.html',{'title':'situation', 'form_path': '/get_observation/', 'message': 'Please insert a situation'})

def stats_view_activities(request):
    s = Sentence.objects.all()[0]
    data = s.get_stats_data()
    return render(request,'stats_view.html',{'page_path':'/stats_Activities/' ,'title': 'stats', 'user': 'Orange Gat', 'labels' : data.keys(), 'logs': data['Activities'], 'category_selected': 'Activities'})

def stats_view_objects(request):
    s = Sentence.objects.all()[0]
    data = s.get_stats_data()
    return render(request,'stats_view.html',{'page_path':'/stats_Objects/' ,'title': 'stats', 'user': 'Orange Gat', 'labels' : data.keys(), 'logs': data['Objects'], 'category_selected': 'Objects'})

def stats_view_contexts(request):
    s = Sentence.objects.all()[0]
    data = s.get_stats_data()
    return render(request,'stats_view.html',{'page_path':'/stats_Contexts/' ,'title': 'stats', 'user': 'Orange Gat', 'labels' : data.keys(), 'logs': data['Contexts'], 'category_selected': 'Contexts'})

def stats_view_emotional_bridge(request):
    s = Sentence.objects.all()[0]
    data = s.get_stats_data()
    return render(request,'stats_view.html',{'page_path':'/stats_Bridges/' ,'title': 'stats', 'user': 'Orange Gat', 'labels' : data.keys(), 'logs': data['Bridges'], 'category_selected': 'Bridges'})

#functionalities
def add_observation(request):
    #pass via post
    if(request.POST['chatbar-message'] != ''):
        s = Sentence(text=str(request.POST['chatbar-message']))
        s.analyzeSentence()
    return render(request, 'chat_view.html', {'title': 'observation', 'message': 'Please insert a new observation'})

def remove_log(request, log_id, target):
    print(log_id, target)
    s = Sentence.objects.all()[0]
    data = s.get_stats_data()
    sentences = Sentence.objects.filter(target=target)
    s = sentences.get(pk=int(log_id))
    s.delete()
    return stats_view_emotional_bridge(request)



def get_observation(request):
    query = request.POST['chatbar-message']
    if(query != ''):
        response, message = Sentence().user_response(query)
        print(response['text'])
        return render(request, 'situation_response.html', {'user_response': response['text'], 'user_query': query, 'message': message , 'id': response['id'], 'form_path':'/get_choice/' })

def get_choice(request):
    query = request.POST['decision'] #"yes" || "no"
    sentence = Sentence.objects.get(pk=request.POST['id'])
    prev_percentage = round(sentence.get_movement_percentage())
    if(query =='yes'):
        sentence.action += 1
        sentence.save()
    else:
        sentence.unaction += 1
        sentence.save()
    new_percentage = round(sentence.get_movement_percentage())
    movement = new_percentage - prev_percentage
    return render(request, 'choice_view.html', {'movement': movement, 'form_path': '/situation/', 'percentage': new_percentage})

mySelfApp/templates/chat_view.html
<!-- DOCTYPE html -->
{%load static%}
 <html lang="es">
	 <head>
		 <title>{{title}}</title>
		 <link rel="stylesheet" href="{% static 'css/background.css' %}" />
		 <link rel="stylesheet" href="{% static 'css/chat.css' %}" />
		 <link rel="stylesheet" href="{% static 'css/page_list.css' %}" />
		 <script src="https://kit.fontawesome.com/51e1fe77b6.js" crossorigin="anonymous"></script>
	 </head>
	 <body>
		<div id="page-list">
			<ul id="page-list-ul">
				<a href="{% url 'myself:main_view' %}"><li>Main page</li></a>
				<a href="{% url 'myself:observation_view' %}"><li>Observations page</li></a>
				<a href="{% url 'myself:situation_view' %}"><li>Situations page</li></a>
				<a href="{% url 'myself:stats_view_emotional_bridge' %}"><li>Stats page</li></a>
			</ul>
		</div>
		 <h1>{{title}}</h1>
		<div id="container">
			<div id="messages">
				<div class="messages messages-bot">{{message}}</div><br>
			</div>
			<div id="chatbar">
				<form action="{{form_path}}" method="POST">
					{% csrf_token %}
					<input type="text" name="chatbar-message" id="chatbar-message-input" />
					<button id="chatbar-message-btn"><i class="fa-solid fa-magnifying-glass"></i></button>
				</form>
			</div>
		</div>	
	 </body>
 </html>

mySelfApp/templates/choice_view.html
<!-- DOCTYPE html5 -->
{% load static %}
<html lang='en'> 
	<head>
		<title>Main page</title>
		<script src="https://kit.fontawesome.com/51e1fe77b6.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'css/background.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/main_view_style.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/choice_view.css' %}"/>
	</head>
	<body>
		<div id="container">
			{% comment %}welcome section{% endcomment %}
			<h1>Welcome back!</h1>
			<h3>Username</h3><br>
			{% comment %}small showing stats section{% endcomment %}
			<p>This was your last movement: </p>
			<h2>{{movement}} %</h2>

			<div id="img"></div>	
			<p>You have {{percentage}}% of loyalty to your words</p>
			{% comment %}options section{% endcomment %}
			<form action="{{form_path}}" method="POST">
				{% csrf_token %}
				<button>Continue</button>
			</form>
		</div>
	</body>
</html>

mySelfApp/templates/main_view.html
<!-- DOCTYPE html5 -->
{% load static %}
<html lang='en'> 
	<head>
		<title>Main page</title>
		<script src="https://kit.fontawesome.com/51e1fe77b6.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'css/background.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/main_view_style.css' %}"/>
	</head>
	<body>
		<div id="container">
			{% comment %}welcome section{% endcomment %}
			<h1>Welcome back!</h1>
			<h3>Orange Gat</h3>
			{% comment %}small showing stats section{% endcomment %}
			<div id="img"></div>	
			<p>You have {{percentage}}% of loyalty to your words</p>
			{% comment %}options section{% endcomment %}
			<h1>Select one of the following features: </h1>
			<div id="options-container">
				<a href="{% url 'myself:observation_view' %}"><div class="option" id="Observations"><i class="fa-solid fa-eye"></i>Observations</div></a>
				<a href="{% url 'myself:situation_view' %}"><div class="option" id="Situations"><i class="fa-solid fa-circle-exclamation"></i>Situations</div></a>
				<a href="{% url 'myself:stats_view_emotional_bridge' %}"><div class="option" id="Stats"><i class="fa-solid fa-database"></i>Stats</div></a>
			</div>
		</div>
	</body>
</html>

mySelfApp/templates/situation_response.html
<!-- DOCTYPE html -->
{%load static%}
 <html lang="es">
	 <head>
		 <title>{{title}}</title>
		 <link rel="stylesheet" href="{% static 'css/background.css' %}" />
		 <link rel="stylesheet" href="{% static 'css/chat.css' %}" />
		 <link rel="stylesheet" href="{% static 'css/page_list.css' %}" />
		 <script src="https://kit.fontawesome.com/51e1fe77b6.js" crossorigin="anonymous"></script>
	 </head>
	 <body>
		<div id="page-list">
			<ul id="page-list-ul">
				<a href="{% url 'myself:main_view' %}"><li>Main page</li></a>
				<a href="{% url 'myself:observation_view' %}"><li>Observations page</li></a>
				<a href="{% url 'myself:situation_view' %}"><li>Situations page</li></a>
				<a href="{% url 'myself:stats_view_emotional_bridge' %}"><li>Stats page</li></a>
			</ul>
		</div>
		 <h1>{{title}}</h1>
		<div id="container">
			<div id="messages">
				<div class="messages messages-bot">Please insert a new observation:</div><br>
				<div class="messages messages-user">{{user_query}}</div><br>
				<div class="messages messages-bot">
					<p>{{message}}</p><br>
					<p>"{{user_response}}"</p>
				</div><br>
				<div class="messages messages-bot">With the information provided, are you going to do something to feel better now? type "y" for yes, and "n" for no.</div><br>
			</div>
			<div id="chatbar">
				<form action="{{form_path}}" method="POST">
					{% csrf_token %}
					<input type="hidden" value="{{id}}" name="id" />
					<button name="decision" value="yes">Yes</button>
					<button name="decision" value="no">No</button>
				</form>
			</div>
		</div>	
	 </body>
 </html>

mySelfApp/templates/stats_view.html
{% load static %}
<!-- DOCTYPE html -->
<html lang="en">
	<head>
		<title>Stats</title>
		<link href="{% static 'css/background.css' %}" rel="stylesheet" />
		<link href="{% static 'css/stats_view_style.css' %}" rel="stylesheet" />
		<link href="{% static 'css/page_list.css' %}" rel="stylesheet" />
		<script src="https://kit.fontawesome.com/51e1fe77b6.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<input type="hidden" id="category-selected" value={{category_selected}} />
		<div id="page-list">
			<ul id="page-list-ul">
				<a href="{% url 'myself:main_view' %}"><li>Main page</li></a>
				<a href="{% url 'myself:observation_view' %}"><li>Observations page</li></a>
				<a href="{% url 'myself:situation_view' %}"><li>Situations page</li></a>
				<a href="{% url 'myself:stats_view_emotional_bridge' %}"><li>Stats page</li></a>
			</ul>
		</div>
		<h1 style="margin-top: 50px">Welcome {{user}}!</h1>
		<p>This is the data we got so far:</p>
		<div id="container">
			<!--I want a horizontal slider with the categories-->
			<h3>Categories: </h3>
			<div id="categories-slider">
				{% for el in labels %}
				<a href="/stats_{{el}}/" method="POST">
					<div class="category {{el}}">
						<p class="category-name">{{el}}</p>
					</div>
				</a>
				{% endfor %}

			</div>
			<!--I want an space where the sentences are displayed like a list with an errase button-->
			<h3>Logs</h3>
			<div id="category-displayed">
				<ul>
					{% for el in logs %}
						<li>
							<form action="/remove_log/{{el.id}}/{{el.target}}/" method="POST">
								{% csrf_token %}
								<p>{{el.text}}</p>
								<input type="hidden" value={{page_path}} name="target" />
								<button class="delete-btn"}><i class="fa-solid fa-trash"></i></i></button>
							</form>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<script src="{% static 'js/stats.js' %}"></script>
	</body>
</html>